spring.application.name=spring-security-jwt
server.port=8005
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=springboot
spring.datasource.username=postgres
spring.datasource.password=postgres

#Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false